"""Import time library."""
from time import time


class Block:
    """A Block of Blockchain.

    Attributes:
    ---------
        index : str
            The index of this block.
        previous_hash : json
            The hash of the previous block in the blockchain.
        timestamp : time
            The timestamp of the block (automatically generated by default).
        transactions : list
            A list of transaction which are included in the block.
        proof : str
            The proof of work number that yielded this block.

    """

    def __init__(
        self, index, previous_hash, transactions, proof, timestamp=time()
    ):
        """Initialize Block."""
        self.index = index
        self.previous_hash = previous_hash
        self.transactions = transactions
        self.proof = proof
        self.timestamp = timestamp

    def __repr__(self):
        """Return a dict of Block."""
        return str(self.__dict__)
